
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["dependencies"]
name = "walytis_beta_api"
authors = [{ name = "emendir" }]
version = "0.1.0"
description = "A library for interacting with Walytis, a flexible, lightweight, nonlinear blockchain. Built to be built upon."
readme = {file = "ReadMe.md", content-type = "text/markdown"}

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["src"]
include = ["walytis_beta_api","walytis_beta_api._experimental"]
namespaces = false 
